---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3372079753-oB1CyUp4163qy263vqZwfQtW7X1kXqaSO6EXF30
:access_token_secret: LLc8D0O6ZBxuzg7E2xqQaHfWv3lXlk5WpyInIHGvbWZ6t
